Repository fga-eps-mds/2023-1-schedula-gerenciador-de-tutoriais, pull requests merged in 2023-06, with the labels that each got.

#6 Fix: Update tutorial check file
  src/tutorials/tutorials.controller.ts
Labels: bug

#7 Sonar: deleting sonar files
  sonar-project.properties
Labels: documentation

#8 Develop
  sonar-project.properties
  src/tutorials/tutorials.controller.ts
Labels: enhancement
